[package]
name = "antidebug-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["debugapi", "sysinfoapi", "memoryapi", "processthreadsapi", "psapi", "winreg", "winerror", "iphlpapi", "mmeapi", "mmsystem"] }